"""Single source of truth for IP/MAC assignment in the Zero Trust SDN topology.

Both simulation/topology.py (which builds the Mininet hosts) and
controller/trust_balancer.py (which needs to know a server's MAC to install a
VIP rewrite rule, without any runtime ARP/discovery) depend on this exact
scheme. If the two ever computed addresses differently, the VIP rewrite would
silently install rules for a MAC nothing owns, and the demo would fail with no
obvious error — so this lives in one place, imported by both.
"""

import re

# Locally-administered (U/L bit set) so it cannot collide with any Mininet
# autogenerated MAC. Nothing else on the network owns this address; the
# controller proxy-ARPs for it and rewrites traffic to/from it.
VIP_MAC = '02:00:00:00:99:01'

_SRV_RE = re.compile(r'^srv(\d+)$')


def srv_ip(i: int) -> str:
    return f'10.0.1.{i}'


def srv_mac(i: int) -> str:
    return '00:00:00:00:01:%02x' % i


def iot_ip(j: int) -> str:
    return f'10.0.0.{j}'


def iot_mac(j: int) -> str:
    return '00:00:00:00:00:%02x' % j


def srv_index(node_id: str) -> int:
    """'srv3' -> 3. Raises ValueError if node_id isn't of that shape."""
    m = _SRV_RE.match(node_id)
    if not m:
        raise ValueError(f"Not a server node id: {node_id!r}")
    return int(m.group(1))
